[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = "@jinja {{ env.SECRET_KEY }}"

[development]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:password@127.0.0.1/virtual-store-dev"

[production]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:secret@127.0.0.1/virtual-store"

[testing]
SQLALCHEMY_DATABASE_URI = "sqlite://"
