[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = "@jinja {{ env.SECRET_KEY }}"

MAIL_SENDER = "@jinja {{ env.MAIL_SENDER }} "
MAIL_SERVER = "@jinja {{ env.MAIL_SERVER }} "
MAIL_PORT = "@jinja {{ env.MAIL_PORT }} "
MAIL_USERNAME = "@jinja {{ env.MAIL_USERNAME }} "
MAIL_PASSWORD = "@jinja {{ env.MAIL_PASSWORD }} "
MAIL_USE_TLS = true
MAIL_USE_SSL = false

[development]
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.DEV_DATABASE }}"

[production]
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.PROD_DATABASE }}"

[testing]
SQLALCHEMY_DATABASE_URI = "@jinja {{ env.TESTING_DATABASE }}"
