[default]
SQLALCHEMY_TRACK_MODIFICATIONS=false

[development]
SQLALCHEMY_DATABASE_URI="postgresql://postgres:password@127.0.0.1/flask-store-dev"

[production]
SQLALCHEMY_DATABASE_URI="postgresql://postgres:secret@127.0.0.1/flask-store"

[testing]
SQLALCHEMY_DATABASE_URI="sqlite://"