"""empty message

Revision ID: 41239a0f7c6e
Revises: a1ec5d6f4cf9
Create Date: 2021-08-10 22:24:42.805506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41239a0f7c6e'
down_revision = 'a1ec5d6f4cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
