"""empty message

Revision ID: c0fd36bb6b9c
Revises: 5facaf2668b7
Create Date: 2021-08-26 22:58:45.970934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fd36bb6b9c'
down_revision = '5facaf2668b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('document_id', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_document_id'), 'profiles', ['document_id'], unique=True)
    op.create_index(op.f('ix_profiles_phone'), 'profiles', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_phone'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_document_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
